version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=carwash
      - DB_PASS=carwash123
      - DB_NAME=carwash
      - DB_PORT=3306
      - DB_DIALECT=mysql
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=carwash
      - MYSQL_USER=carwash
      - MYSQL_PASSWORD=carwash123
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: 