-- MySQL Script generated by MySQL Workbench
-- Sun Mar 16 00:54:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car-wash
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `car-wash` ;

-- -----------------------------------------------------
-- Schema car-wash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car-wash` DEFAULT CHARACTER SET utf8 ;
USE `car-wash` ;

-- -----------------------------------------------------
-- Table `car-wash`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Users` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `acc_type` ENUM('user', 'employee') NOT NULL,
  `profile_picture_url` TEXT NULL,
  `name` VARCHAR(70) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `users_username_unique` (`username` ASC) VISIBLE,
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `car-wash`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Company` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Company` (
  `company_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `location` TEXT NOT NULL,
  `logo_url` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `approved` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `company_company_name_unique` (`company_name` ASC) VISIBLE,
  UNIQUE INDEX `company_email_unique` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `car-wash`.`CompanyDocuments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`CompanyDocuments` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`CompanyDocuments` (
  `document_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `document_type` VARCHAR(255) NOT NULL,
  `document_url` VARCHAR(255) NOT NULL,
  `upload_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `companydocuments_company_id_foreign` (`company_id` ASC) VISIBLE,
  CONSTRAINT `companydocuments_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Employee` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Employee` (
  `user_id` INT UNSIGNED NOT NULL,
  `company_id` INT UNSIGNED NOT NULL,
  `role` ENUM('super-admin', 'manager', 'employee') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `employees_company_id_foreign` (`company_id` ASC) VISIBLE,
  INDEX `employees_user_id_foreign` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `company_id`),
  CONSTRAINT `employees_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`),
  CONSTRAINT `employees_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `car-wash`.`Users` (`user_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Products` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Products` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `stock` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`),
  INDEX `products_company_id_foreign` (`company_id` ASC) VISIBLE,
  CONSTRAINT `products_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Category` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Category` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`PaymentMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`PaymentMethod` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`PaymentMethod` (
  `payment_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `public_key` VARCHAR(100) NOT NULL,
  `secret_key` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Orders` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Orders` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `company_id` INT UNSIGNED NOT NULL,
  `order_type` ENUM('product', 'wash', 'rental') NOT NULL,
  `order_date` TIMESTAMP NOT NULL,
  `total_amount` DECIMAL(8,2) NOT NULL,
  `payment_method_id` TINYINT UNSIGNED NOT NULL,
  `payment_gateway_response` TEXT NOT NULL,
  `shipping_address` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  INDEX `orders_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `orders_company_id_foreign` (`company_id` ASC) VISIBLE,
  INDEX `fk_Orders_PaymentMethod1_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `orders_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `car-wash`.`Users` (`user_id`),
  CONSTRAINT `orders_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`),
  CONSTRAINT `fk_Orders_PaymentMethod1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `car-wash`.`PaymentMethod` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`OrderItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`OrderItems` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`OrderItems` (
  `order_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_items_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `order_items_order_id_foreign` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order_items_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `car-wash`.`Products` (`product_id`),
  CONSTRAINT `order_items_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `car-wash`.`Orders` (`order_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`CustomerCar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`CustomerCar` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`CustomerCar` (
  `customer_car_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` TINYTEXT NOT NULL,
  `car_plate_number` TINYTEXT NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`customer_car_id`),
  INDEX `fk_CustomerCar_Users1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerCar_Users1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `car-wash`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`CarWashOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`CarWashOrders` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`CarWashOrders` (
  `wash_order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `within_company` TINYINT NOT NULL COMMENT 'if it is indoors or within company\\\'s workshop',
  `location` TEXT NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `customer_car_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`wash_order_id`),
  INDEX `car_wash_orders_order_id_foreign` (`order_id` ASC) VISIBLE,
  INDEX `fk_Car_Wash_Orders_Users1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Car_Wash_Orders_CustomerCar1_idx` (`customer_car_id` ASC) VISIBLE,
  CONSTRAINT `car_wash_orders_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `car-wash`.`Orders` (`order_id`),
  CONSTRAINT `fk_Car_Wash_Orders_Users1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `car-wash`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_Wash_Orders_CustomerCar1`
    FOREIGN KEY (`customer_car_id`)
    REFERENCES `car-wash`.`CustomerCar` (`customer_car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`CompanyExhibition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`CompanyExhibition` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`CompanyExhibition` (
  `exhibition_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(255) NOT NULL,
  `company_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`exhibition_id`),
  INDEX `fk_CompanyExhibition_Company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_CompanyExhibition_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Cars` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Cars` (
  `car_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `year` INT NOT NULL,
  `price_per_day` DECIMAL(8,2) NOT NULL,
  `exhibition_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `cars_company_id_foreign` (`company_id` ASC) VISIBLE,
  INDEX `fk_Cars_CompanyExhibition1_idx` (`exhibition_id` ASC) VISIBLE,
  CONSTRAINT `cars_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`),
  CONSTRAINT `fk_Cars_CompanyExhibition1`
    FOREIGN KEY (`exhibition_id`)
    REFERENCES `car-wash`.`CompanyExhibition` (`exhibition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`RentalOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`RentalOrders` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`RentalOrders` (
  `rental_order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `car_id` INT UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`rental_order_id`),
  INDEX `rental_orders_car_id_foreign` (`car_id` ASC) VISIBLE,
  INDEX `rental_orders_order_id_foreign` (`order_id` ASC) VISIBLE,
  CONSTRAINT `rental_orders_car_id_foreign`
    FOREIGN KEY (`car_id`)
    REFERENCES `car-wash`.`Cars` (`car_id`),
  CONSTRAINT `rental_orders_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `car-wash`.`Orders` (`order_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`OrderStatusHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`OrderStatusHistory` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`OrderStatusHistory` (
  `status_history_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `status` ENUM('pending', 'complete') NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`status_history_id`),
  INDEX `order_status_history_order_id_foreign` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order_status_history_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `car-wash`.`Orders` (`order_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`Ratings` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`Ratings` (
  `company_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `rating_value` DECIMAL(8,2) NOT NULL,
  `review_text` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`, `user_id`),
  INDEX `ratings_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `ratings_company_id_foreign` (`company_id` ASC) VISIBLE,
  CONSTRAINT `ratings_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `car-wash`.`Users` (`user_id`),
  CONSTRAINT `ratings_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `car-wash`.`Company` (`company_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`SubCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`SubCategory` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`SubCategory` (
  `sub_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`sub_category_id`),
  INDEX `sub_category_category_id_foreign` (`category_id` ASC) VISIBLE,
  CONSTRAINT `sub_category_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `car-wash`.`Category` (`category_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`SubCatProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`SubCatProduct` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`SubCatProduct` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `sub_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sub_cat_product_sub_category_id_foreign` (`sub_category_id` ASC) VISIBLE,
  INDEX `sub_cat_product_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `sub_cat_product_sub_category_id_foreign`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `car-wash`.`SubCategory` (`sub_category_id`),
  CONSTRAINT `sub_cat_product_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `car-wash`.`Products` (`product_id`));


-- -----------------------------------------------------
-- Table `car-wash`.`RentalCarsImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`RentalCarsImages` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`RentalCarsImages` (
  `image_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NOT NULL,
  `car_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `fk_RentalCarsImages_Cars1_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `fk_RentalCarsImages_Cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `car-wash`.`Cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `car-wash`.`WashOrderOperation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`WashOrderOperation` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`WashOrderOperation` (
  `wash_order_id` INT UNSIGNED NOT NULL,
  `employee_assigned_id` INT UNSIGNED NOT NULL,
  `operation_start_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `operation_done_at` DATETIME NULL,
  `company_id` INT UNSIGNED NOT NULL,
  INDEX `operation_wash_order_fk_idx` (`wash_order_id` ASC) VISIBLE,
  PRIMARY KEY (`wash_order_id`),
  INDEX `fk_WashOrderOperation_Employees1_idx` (`employee_assigned_id` ASC, `company_id` ASC) VISIBLE,
  CONSTRAINT `operation_wash_order_fk`
    FOREIGN KEY (`wash_order_id`)
    REFERENCES `car-wash`.`CarWashOrders` (`wash_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WashOrderOperation_Employees1`
    FOREIGN KEY (`employee_assigned_id` , `company_id`)
    REFERENCES `car-wash`.`Employee` (`user_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-wash`.`ProductsImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car-wash`.`ProductsImages` ;

CREATE TABLE IF NOT EXISTS `car-wash`.`ProductsImages` (
  `image_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `fk_ProductsImages_Products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_ProductsImages_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `car-wash`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
